url: http://nazhao-ai.github.io
baseurl: ""

# Site Settings
title: Na Zhao
description: "Na Zhao Homepage"
keywords: "Na Zhao, Dentist"
collections:
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown
exclude: ["Rakefile", "LICENSE", "readme.markdown"]
